theme: jekyll-theme-minimal
title: Zebrok and Ryt homepage
description: Bookmark this to keep an eye on my project updates!
lsi: false
safe: true
source: [kamizebrok.github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
